name: Build and Deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Устанавливаем Docker (если требуется, Docker обычно уже есть на ubuntu-latest)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 3: Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 4: Собираем Docker образ
      - name: Build Docker image
        run: docker build -t sorenty/order-managment-backend:latest ./backend

      # Шаг 5: Пушим образ в Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push sorenty/order-managment-backend:latest

      # Шаг 6: Запускаем контейнер в фоновом режиме
      - name: Start backend container
        run: docker run -d --name backend-test -p 5000:5000 sorenty/order-managment-backend:latest

      # Шаг 7: Ждем, пока сервер будет готов
      - name: Wait for the server to start
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000 > /dev/null; then
              echo "Server is ready."
              exit 0
            fi
            echo "Waiting for server..."
            sleep 5
          done
          echo "Server did not start in time."
          exit 1

      # Шаг 8: Проверяем работу контейнера
      - name: Test backend container
        run: curl http://localhost:5000

      # Шаг 9: Останавливаем и удаляем контейнер
      - name: Stop and remove backend container
        run: docker stop backend-test && docker rm backend-test
